/*
  Auto-generated by Spline
*/

export const TopAside = () => {
  const hasWindow = typeof window !== "undefined";
  return (
    <div className="heroAside">
      <iframe
        src="https://my.spline.design/main-bdf9f914a372467f06ea141d2dbc0677/"
        frameborder="0"
        width={600}
        height={600}
      />
    </div>
  );
};

export default TopAside;
