/*
  Auto-generated by Spline
*/

import dynamic from "next/dynamic";
// import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

// const Spline = dynamic(() => import("@splinetool/react-spline"), {
//   ssr: false,
// });

// const useSpline = dynamic(() => import("@splinetool/r3f-spline"), {
//   ssr: false,
// });

export const TopAside = () => {
  const hasWindow = typeof window !== "undefined";
  return (
    <div className="heroAside">
      <iframe
        src="https://my.spline.design/main-bdf9f914a372467f06ea141d2dbc0677/"
        frameborder="0"
        width={600}
        height={600}
        // width={hasWindow ? window.innerHeight * 0.4 : 0}
        // height={hasWindow ? window.innerHeight * 0.4 : 0}
      />
    </div>

    // <div>
    //   <Spline scene="https://prod.spline.design/gfNuRPpbpRrfm7Va/scene.splinecode" />
    // </div>

    // <div style={{ maxHeight: "70vh" }}>
    //   <color attach="background" args={["#fefefe"]} />
    //   <group dispose={null}>
    //     <mesh
    //       name="hand 3"
    //       geometry={nodes["hand 3"].geometry}
    //       material={nodes["hand 3"].material}
    //       castShadow
    //       receiveShadow
    //       position={[-445.28, 181.89, -148.88]}
    //       rotation={[1.59, -0.87, 1.85]}
    //       scale={[3.5, 4, 4]}
    //     />
    //     <mesh
    //       name="hand 2"
    //       geometry={nodes["hand 2"].geometry}
    //       material={nodes["hand 2"].material}
    //       castShadow
    //       receiveShadow
    //       position={[-181.93, 316.93, -126.89]}
    //       rotation={[1.83, -1.18, 2.05]}
    //       scale={[3.5, 4, 4]}
    //     />
    //     <mesh
    //       name="Sphere"
    //       geometry={nodes.Sphere.geometry}
    //       material={materials["Sphere Material"]}
    //       castShadow
    //       receiveShadow
    //       rotation={[0, 4.6, 0]}
    //     />
    //     <directionalLight
    //       name="Directional Light"
    //       castShadow
    //       intensity={0.7}
    //       shadow-mapSize-width={1024}
    //       shadow-mapSize-height={1024}
    //       shadow-camera-near={-10000}
    //       shadow-camera-far={100000}
    //       shadow-camera-left={-500}
    //       shadow-camera-right={500}
    //       shadow-camera-top={500}
    //       shadow-camera-bottom={-500}
    //       position={[-936.77, -359.32, 649.42]}
    //     />
    //     <mesh
    //       name="hand"
    //       geometry={nodes.hand.geometry}
    //       material={nodes.hand.material}
    //       castShadow
    //       receiveShadow
    //       position={[-350.15, 336.24, -161.14]}
    //       rotation={[1.73, -1.09, 1.96]}
    //       scale={4}
    //     />
    //     <OrthographicCamera
    //       name="Personal Camera"
    //       makeDefault={true}
    //       zoom={1.51}
    //       far={100000}
    //       near={-100000}
    //       position={[-515.3, 496.68, 841.55]}
    //       rotation={[-0.15, -0.24, -0.04]}
    //     />
    //     <hemisphereLight
    //       name="Default Ambient Light"
    //       intensity={0.75}
    //       color="#494949"
    //       position={[0, 1, 0]}
    //     />
    //   </group>
    // </div>
  );
};

export default TopAside;
