const DEFAULT_TITLE = "UAlberta CS";
const DEFAULT_DESCRIPTION =
  "UAlberta CS Website - Our demands and our vision ✊";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "UAlberta Contributors",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["ualberta", "alberta", "university"],
  DEFAULT_SITE_NAME: "UAlberta CS",
  DEFAULT_BASE_URL: "",
  DEFAULT_PREVIEW_IMG: "",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "",
};

export default CONSTANTS;
